# Generated by Django 2.2.14 on 2020-07-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
