# Generated by Django 2.2.14 on 2020-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0002_auto_20200728_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
