# Generated by Django 2.2.14 on 2020-07-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0004_auto_20200728_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
