# Generated by Django 2.2.14 on 2020-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'custom',
            },
        ),
    ]
