# Generated by Django 2.2.14 on 2020-08-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBmigrate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wife',
        ),
    ]
