# Generated by Django 2.2.14 on 2020-07-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
