# Generated by Django 2.2.14 on 2020-07-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200727_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
