# Generated by Django 2.2.14 on 2020-07-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_man_woman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woman',
            old_name='woman',
            new_name='man',
        ),
    ]
